### ISSUE TITLE
how to use it on the liked songs "playlist"?

### ISSUE THREAD

**Issue by Turhvjbufv** [zWolfrost/spotify-dlp#1]

**Comment by zWolfrost** [comment]
You could probably just select all songs in the liked playlist on Spotify Desktop by pressing Control + A (or alternatively shift+clicking the first and last songs on the browser version), and then right-clicking and add to an actual playlist.

**Comment by zWolfrost** [comment]
Looks like spotify is limiting the amount of tracks the program can get. I will try to make an update to fix that. In the meantime, If it's feasable to make a playlist for every 100 tracks, you can do try as a workaround.

**Comment by zWolfrost** [comment]
I forgot to tell you I did manage to fix this issue yesterday, in v2.1.0. If you still need the thing to download your entire playlist, now it's possible :)
